webtalk_init -webtalk_dir /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.sdk/webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "2018-10-13 19:12:22" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2018.2" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "1uce5ro2qdl97lgi1b0bk56g71" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2018.2_1" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Ubuntu" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Ubuntu 18.04.1 LTS" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-7500U CPU @ 2.70GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3500.046 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8,199 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1539446703000" -context "sdk\\\\hardware/1539446703000"
webtalk_add_data -client sdk -key isZynq -value "true" -context "sdk\\\\hardware/1539446703000"
webtalk_add_data -client sdk -key isZynqMP -value "false" -context "sdk\\\\hardware/1539446703000"
webtalk_add_data -client sdk -key Processors -value "3" -context "sdk\\\\hardware/1539446703000"
webtalk_add_data -client sdk -key VivadoVersion -value "2018.2.2" -context "sdk\\\\hardware/1539446703000"
webtalk_add_data -client sdk -key Arch -value "zynq" -context "sdk\\\\hardware/1539446703000"
webtalk_add_data -client sdk -key Device -value "7z020" -context "sdk\\\\hardware/1539446703000"
webtalk_add_data -client sdk -key IsHandoff -value "true" -context "sdk\\\\hardware/1539446703000"
webtalk_add_data -client sdk -key os -value "NA" -context "sdk\\\\hardware/1539446703000"
webtalk_add_data -client sdk -key apptemplate -value "NA" -context "sdk\\\\hardware/1539446703000"
webtalk_add_data -client sdk -key RecordType -value "HWCreation" -context "sdk\\\\hardware/1539446703000"
webtalk_add_data -client sdk -key uid -value "1539450260000" -context "sdk\\\\bsp/1539450260000"
webtalk_add_data -client sdk -key hwid -value "1539446703000" -context "sdk\\\\bsp/1539450260000"
webtalk_add_data -client sdk -key os -value "freertos10_xilinx" -context "sdk\\\\bsp/1539450260000"
webtalk_add_data -client sdk -key apptemplate -value "freertos_hello_world" -context "sdk\\\\bsp/1539450260000"
webtalk_add_data -client sdk -key RecordType -value "BSPCreation" -context "sdk\\\\bsp/1539450260000"
webtalk_add_data -client sdk -key uid -value "1539450261000" -context "sdk\\\\application/1539450261000"
webtalk_add_data -client sdk -key hwid -value "1539446703000" -context "sdk\\\\application/1539450261000"
webtalk_add_data -client sdk -key bspid -value "1539450260000" -context "sdk\\\\application/1539450261000"
webtalk_add_data -client sdk -key newbsp -value "true" -context "sdk\\\\application/1539450261000"
webtalk_add_data -client sdk -key os -value "freertos10_xilinx" -context "sdk\\\\application/1539450261000"
webtalk_add_data -client sdk -key apptemplate -value "freertos_hello_world" -context "sdk\\\\application/1539450261000"
webtalk_add_data -client sdk -key RecordType -value "APPCreation" -context "sdk\\\\application/1539450261000"
webtalk_add_data -client sdk -key LangUsed -value "C" -context "sdk\\\\application/1539450261000"
webtalk_add_data -client sdk -key Procused -value "microblaze" -context "sdk\\\\application/1539450261000"
webtalk_add_data -client sdk -key projSize -value "138.3359375" -context "sdk\\\\application/1539450261000"
webtalk_add_data -client sdk -key uid -value "NA" -context "sdk\\\\bsp/1539450742576"
webtalk_add_data -client sdk -key RecordType -value "ToolUsage" -context "sdk\\\\bsp/1539450742576"
webtalk_add_data -client sdk -key BootgenCount -value "0" -context "sdk\\\\bsp/1539450742576"
webtalk_add_data -client sdk -key DebugCount -value "0" -context "sdk\\\\bsp/1539450742576"
webtalk_add_data -client sdk -key PerfCount -value "0" -context "sdk\\\\bsp/1539450742576"
webtalk_add_data -client sdk -key FlashCount -value "0" -context "sdk\\\\bsp/1539450742576"
webtalk_add_data -client sdk -key CrossTriggCount -value "0" -context "sdk\\\\bsp/1539450742576"
webtalk_add_data -client sdk -key QemuDebugCount -value "0" -context "sdk\\\\bsp/1539450742576"
webtalk_transmit -clientid 505775809 -regid "" -xml /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.sdk/webtalk/usage_statistics_ext_sdk.xml -html /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.sdk/webtalk/usage_statistics_ext_sdk.html -wdm /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.sdk/webtalk/sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
