# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_lmb_bram_0/MB_freeRTOS_lmb_bram_0.xci
# IP: The module: 'MB_freeRTOS_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_lmb_bram_0/MB_freeRTOS_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_freeRTOS_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_lmb_bram_0/MB_freeRTOS_lmb_bram_0.xci
# IP: The module: 'MB_freeRTOS_lmb_bram_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_lmb_bram_0/MB_freeRTOS_lmb_bram_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'MB_freeRTOS_lmb_bram_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
