# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/1.0/PYNQ-Z1_C.xdc

# Block Designs: bd/MB_freeRTOS/MB_freeRTOS.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS || ORIG_REF_NAME==MB_freeRTOS} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_microblaze_0_0/MB_freeRTOS_microblaze_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_microblaze_0_0 || ORIG_REF_NAME==MB_freeRTOS_microblaze_0_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_microblaze_0_axi_periph_0/MB_freeRTOS_microblaze_0_axi_periph_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_microblaze_0_axi_periph_0 || ORIG_REF_NAME==MB_freeRTOS_microblaze_0_axi_periph_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_microblaze_0_axi_intc_0/MB_freeRTOS_microblaze_0_axi_intc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_microblaze_0_axi_intc_0 || ORIG_REF_NAME==MB_freeRTOS_microblaze_0_axi_intc_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_mdm_1_0/MB_freeRTOS_mdm_1_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_mdm_1_0 || ORIG_REF_NAME==MB_freeRTOS_mdm_1_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_rst_clk_wiz_1_100M_0/MB_freeRTOS_rst_clk_wiz_1_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_rst_clk_wiz_1_100M_0 || ORIG_REF_NAME==MB_freeRTOS_rst_clk_wiz_1_100M_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_processing_system7_0_0/MB_freeRTOS_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_processing_system7_0_0 || ORIG_REF_NAME==MB_freeRTOS_processing_system7_0_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_axi_timer_0_0/MB_freeRTOS_axi_timer_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_axi_timer_0_0 || ORIG_REF_NAME==MB_freeRTOS_axi_timer_0_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_xbar_0/MB_freeRTOS_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_xbar_0 || ORIG_REF_NAME==MB_freeRTOS_xbar_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_dlmb_v10_0/MB_freeRTOS_dlmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_dlmb_v10_0 || ORIG_REF_NAME==MB_freeRTOS_dlmb_v10_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_ilmb_v10_0/MB_freeRTOS_ilmb_v10_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_ilmb_v10_0 || ORIG_REF_NAME==MB_freeRTOS_ilmb_v10_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_dlmb_bram_if_cntlr_0/MB_freeRTOS_dlmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_dlmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_freeRTOS_dlmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_ilmb_bram_if_cntlr_0/MB_freeRTOS_ilmb_bram_if_cntlr_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_ilmb_bram_if_cntlr_0 || ORIG_REF_NAME==MB_freeRTOS_ilmb_bram_if_cntlr_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_lmb_bram_0/MB_freeRTOS_lmb_bram_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_lmb_bram_0 || ORIG_REF_NAME==MB_freeRTOS_lmb_bram_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_s01_mmu_0/MB_freeRTOS_s01_mmu_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_s01_mmu_0 || ORIG_REF_NAME==MB_freeRTOS_s01_mmu_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_auto_pc_0/MB_freeRTOS_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_auto_pc_0 || ORIG_REF_NAME==MB_freeRTOS_auto_pc_0} -quiet] -quiet

# IP: bd/MB_freeRTOS/ip/MB_freeRTOS_auto_pc_1/MB_freeRTOS_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==MB_freeRTOS_auto_pc_1 || ORIG_REF_NAME==MB_freeRTOS_auto_pc_1} -quiet] -quiet

# XDC: bd/MB_freeRTOS/MB_freeRTOS_ooc.xdc
