# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7z020clg400-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.cache/wt [current_project]
set_property parent.project_path /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.xpr [current_project]
set_property XPM_LIBRARIES {XPM_CDC XPM_FIFO XPM_MEMORY} [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part www.digilentinc.com:pynq-z1:part0:1.0 [current_project]
set_property ip_repo_paths /media/jdm/JDM/Git/reconrtos/Code/Training/CortexM1_Intro [current_project]
set_property ip_output_repo /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_verilog -library xil_defaultlib /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/hdl/MB_freeRTOS_wrapper.v
add_files /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/MB_freeRTOS.bd
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_microblaze_0_0/MB_freeRTOS_microblaze_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_microblaze_0_0/MB_freeRTOS_microblaze_0_0_ooc_debug.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_microblaze_0_0/MB_freeRTOS_microblaze_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_microblaze_0_axi_intc_0/MB_freeRTOS_microblaze_0_axi_intc_0.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_microblaze_0_axi_intc_0/MB_freeRTOS_microblaze_0_axi_intc_0_clocks.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_microblaze_0_axi_intc_0/MB_freeRTOS_microblaze_0_axi_intc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_mdm_1_0/MB_freeRTOS_mdm_1_0.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_mdm_1_0/MB_freeRTOS_mdm_1_0_ooc_trace.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_rst_clk_wiz_1_100M_0/MB_freeRTOS_rst_clk_wiz_1_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_rst_clk_wiz_1_100M_0/MB_freeRTOS_rst_clk_wiz_1_100M_0.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_rst_clk_wiz_1_100M_0/MB_freeRTOS_rst_clk_wiz_1_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_processing_system7_0_0/MB_freeRTOS_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_axi_timer_0_0/MB_freeRTOS_axi_timer_0_0.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_axi_timer_0_0/MB_freeRTOS_axi_timer_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_xbar_0/MB_freeRTOS_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_dlmb_v10_0/MB_freeRTOS_dlmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_dlmb_v10_0/MB_freeRTOS_dlmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_ilmb_v10_0/MB_freeRTOS_ilmb_v10_0.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_ilmb_v10_0/MB_freeRTOS_ilmb_v10_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_dlmb_bram_if_cntlr_0/MB_freeRTOS_dlmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_ilmb_bram_if_cntlr_0/MB_freeRTOS_ilmb_bram_if_cntlr_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_lmb_bram_0/MB_freeRTOS_lmb_bram_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_s01_mmu_0/MB_freeRTOS_s01_mmu_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_auto_pc_0/MB_freeRTOS_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/ip/MB_freeRTOS_auto_pc_1/MB_freeRTOS_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/sources_1/bd/MB_freeRTOS/MB_freeRTOS_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/constrs_1/imports/1.0/PYNQ-Z1_C.xdc
set_property used_in_implementation false [get_files /media/jdm/JDM/Git/reconrtos/Code/Training/MicroBlaze_freeRTOS_HelloWorld/MicroBlaze_freeRTOS_HelloWorld.srcs/constrs_1/imports/1.0/PYNQ-Z1_C.xdc]

read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
set_param ips.enableIPCacheLiteLoad 0
close [open __synthesis_is_running__ w]

synth_design -top MB_freeRTOS_wrapper -part xc7z020clg400-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef MB_freeRTOS_wrapper.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file MB_freeRTOS_wrapper_utilization_synth.rpt -pb MB_freeRTOS_wrapper_utilization_synth.pb"
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
